
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create an IAM role needed by ECS cluster instances.

Resources:

  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['ecs:CreateCluster', 'ecs:DeregisterContainerInstance', 'ecs:DiscoverPollEndpoint',
              'ecs:Poll', 'ecs:RegisterContainerInstance', 'ecs:StartTelemetrySession',
              'ecs:Submit*', 'logs:CreateLogStream', 'logs:PutLogEvents', 'logs:CreateLogGroup','logs:DescribeLogStreams',
              'ecr:BatchCheckLayerAvailability','ecr:BatchGetImage','ecr:GetDownloadUrlForLayer','ecr:GetAuthorizationToken']
            Resource: '*'

Outputs:

  ECSRoleArn:
    Value: !GetAtt ECSRole.Arn

  ECSRoleName:
    Value: !Ref ECSRole
    Export:
      Name: !Sub "${AWS::StackName}-ECSRole"